var namespaceboost_1_1boost =
[
    [ "dispatch", null, [
      [ "ext", null, [
        [ "default_site", "structboost_1_1boost_1_1dispatch_1_1ext_1_1default__site.html", null ],
        [ "hierarchy_of", "structboost_1_1boost_1_1dispatch_1_1ext_1_1hierarchy__of.html", null ],
        [ "model_of", "structboost_1_1boost_1_1dispatch_1_1ext_1_1model__of.html", null ],
        [ "property_of", "structboost_1_1boost_1_1dispatch_1_1ext_1_1property__of.html", "structboost_1_1boost_1_1dispatch_1_1ext_1_1property__of" ],
        [ "scalar_of", "structboost_1_1boost_1_1dispatch_1_1ext_1_1scalar__of.html", null ],
        [ "value_of", "structboost_1_1boost_1_1dispatch_1_1ext_1_1value__of.html", null ],
        [ "value_of_cv< T const, Enable >", "structboost_1_1boost_1_1dispatch_1_1ext_1_1value__of__cv_3_01T_01const_00_01Enable_01_4.html", null ]
      ] ],
      [ "abstract_", "structboost_1_1boost_1_1dispatch_1_1abstract__.html", null ],
      [ "arithmetic_", "structboost_1_1boost_1_1dispatch_1_1arithmetic__.html", null ],
      [ "as_", "structboost_1_1boost_1_1dispatch_1_1as__.html", "structboost_1_1boost_1_1dispatch_1_1as__" ],
      [ "as_integer", "structboost_1_1boost_1_1dispatch_1_1as__integer.html", null ],
      [ "as_unsigned", "structboost_1_1boost_1_1dispatch_1_1as__unsigned.html", null ],
      [ "behave_as", "structboost_1_1boost_1_1dispatch_1_1behave__as.html", null ],
      [ "bool_", "structboost_1_1boost_1_1dispatch_1_1bool__.html", null ],
      [ "constant_", "structboost_1_1boost_1_1dispatch_1_1constant__.html", null ],
      [ "constant_value_", "structboost_1_1boost_1_1dispatch_1_1constant__value__.html", null ],
      [ "cpu_", "structboost_1_1boost_1_1dispatch_1_1cpu__.html", null ],
      [ "cumulative_", "structboost_1_1boost_1_1dispatch_1_1cumulative__.html", null ],
      [ "double_", "structboost_1_1boost_1_1dispatch_1_1double__.html", null ],
      [ "elementwise_", "structboost_1_1boost_1_1dispatch_1_1elementwise__.html", null ],
      [ "error_", "structboost_1_1boost_1_1dispatch_1_1error__.html", null ],
      [ "factory_of", "structboost_1_1boost_1_1dispatch_1_1factory__of.html", null ],
      [ "floating_", "structboost_1_1boost_1_1dispatch_1_1floating__.html", null ],
      [ "formal_", "structboost_1_1boost_1_1dispatch_1_1formal__.html", null ],
      [ "function_", "structboost_1_1boost_1_1dispatch_1_1function__.html", null ],
      [ "functor", "structboost_1_1boost_1_1dispatch_1_1functor.html", null ],
      [ "fundamental_", "structboost_1_1boost_1_1dispatch_1_1fundamental__.html", null ],
      [ "generic_", "structboost_1_1boost_1_1dispatch_1_1generic__.html", null ],
      [ "hierarchy_of", "structboost_1_1boost_1_1dispatch_1_1hierarchy__of.html", null ],
      [ "integer_", "structboost_1_1boost_1_1dispatch_1_1integer__.html", null ],
      [ "integral_", "structboost_1_1boost_1_1dispatch_1_1integral__.html", null ],
      [ "ints_", "structboost_1_1boost_1_1dispatch_1_1ints__.html", null ],
      [ "long_double_", "structboost_1_1boost_1_1dispatch_1_1long__double__.html", null ],
      [ "make_integer", "structboost_1_1boost_1_1dispatch_1_1make__integer.html", null ],
      [ "model_of", "structboost_1_1boost_1_1dispatch_1_1model__of.html", null ],
      [ "primitive_of", "structboost_1_1boost_1_1dispatch_1_1primitive__of.html", null ],
      [ "property_of", "structboost_1_1boost_1_1dispatch_1_1property__of.html", null ],
      [ "reduction_", "structboost_1_1boost_1_1dispatch_1_1reduction__.html", null ],
      [ "scalar_", "structboost_1_1boost_1_1dispatch_1_1scalar__.html", null ],
      [ "scalar_of", "structboost_1_1boost_1_1dispatch_1_1scalar__of.html", null ],
      [ "sign_of", "structboost_1_1boost_1_1dispatch_1_1sign__of.html", null ],
      [ "signed_integral_", "structboost_1_1boost_1_1dispatch_1_1signed__integral__.html", null ],
      [ "signed_type_", "structboost_1_1boost_1_1dispatch_1_1signed__type__.html", null ],
      [ "signed_type_< T, signed >", "structboost_1_1boost_1_1dispatch_1_1signed__type___3_01T_00_01signed_01_4.html", null ],
      [ "signed_type_< T, unsigned >", "structboost_1_1boost_1_1dispatch_1_1signed__type___3_01T_00_01unsigned_01_4.html", null ],
      [ "single_", "structboost_1_1boost_1_1dispatch_1_1single__.html", null ],
      [ "sized_type_", "structboost_1_1boost_1_1dispatch_1_1sized__type__.html", null ],
      [ "target_", "structboost_1_1boost_1_1dispatch_1_1target__.html", "structboost_1_1boost_1_1dispatch_1_1target__" ],
      [ "tieable_", "structboost_1_1boost_1_1dispatch_1_1tieable__.html", null ],
      [ "type_", "structboost_1_1boost_1_1dispatch_1_1type__.html", null ],
      [ "unknown_", "structboost_1_1boost_1_1dispatch_1_1unknown__.html", null ],
      [ "unspecified_", "structboost_1_1boost_1_1dispatch_1_1unspecified__.html", null ],
      [ "value_of", "structboost_1_1boost_1_1dispatch_1_1value__of.html", null ],
      [ "void_", "structboost_1_1boost_1_1dispatch_1_1void__.html", null ]
    ] ],
    [ "simd", null, [
      [ "ext", null, [
        [ "abi_of", "structboost_1_1boost_1_1simd_1_1ext_1_1abi__of.html", null ],
        [ "as_simd", "structboost_1_1boost_1_1simd_1_1ext_1_1as__simd.html", null ]
      ] ],
      [ "abi_of", "structboost_1_1boost_1_1simd_1_1abi__of.html", null ],
      [ "aggregate_storage", "structboost_1_1boost_1_1simd_1_1aggregate__storage.html", null ],
      [ "avx2_", "structboost_1_1boost_1_1simd_1_1avx2__.html", null ],
      [ "avx_", "structboost_1_1boost_1_1simd_1_1avx__.html", null ],
      [ "expected_cardinal", "structboost_1_1boost_1_1simd_1_1expected__cardinal.html", null ],
      [ "fma3_", "structboost_1_1boost_1_1simd_1_1fma3__.html", null ],
      [ "fma4_", "structboost_1_1boost_1_1simd_1_1fma4__.html", null ],
      [ "is_logical_mask", "structboost_1_1boost_1_1simd_1_1is__logical__mask.html", null ],
      [ "limits", "structboost_1_1boost_1_1simd_1_1limits.html", "structboost_1_1boost_1_1simd_1_1limits" ],
      [ "logical", "structboost_1_1boost_1_1simd_1_1logical.html", "structboost_1_1boost_1_1simd_1_1logical" ],
      [ "logical_", "structboost_1_1boost_1_1simd_1_1logical__.html", null ],
      [ "native_cardinal", "structboost_1_1boost_1_1simd_1_1native__cardinal.html", null ],
      [ "native_storage", "structboost_1_1boost_1_1simd_1_1native__storage.html", null ],
      [ "pack_", "structboost_1_1boost_1_1simd_1_1pack__.html", null ],
      [ "real_of", "structboost_1_1boost_1_1simd_1_1real__of.html", null ],
      [ "scalar_storage", "structboost_1_1boost_1_1simd_1_1scalar__storage.html", null ],
      [ "simd_", "structboost_1_1boost_1_1simd_1_1simd__.html", null ],
      [ "simd_emulation_", "structboost_1_1boost_1_1simd_1_1simd__emulation__.html", null ],
      [ "sse1_", "structboost_1_1boost_1_1simd_1_1sse1__.html", null ],
      [ "sse2_", "structboost_1_1boost_1_1simd_1_1sse2__.html", null ],
      [ "sse3_", "structboost_1_1boost_1_1simd_1_1sse3__.html", null ],
      [ "sse4_1_", "structboost_1_1boost_1_1simd_1_1sse4__1__.html", null ],
      [ "sse4_2_", "structboost_1_1boost_1_1simd_1_1sse4__2__.html", null ],
      [ "sse4a_", "structboost_1_1boost_1_1simd_1_1sse4a__.html", null ],
      [ "sse_", "structboost_1_1boost_1_1simd_1_1sse__.html", null ],
      [ "ssse3_", "structboost_1_1boost_1_1simd_1_1ssse3__.html", null ],
      [ "vmx_", "structboost_1_1boost_1_1simd_1_1vmx__.html", null ],
      [ "xop_", "structboost_1_1boost_1_1simd_1_1xop__.html", null ]
    ] ]
];